### ISSUE TITLE
We need a logo

### ISSUE THREAD

**Issue by sreecodeslayer** [silicon-labs/silicon-labs.github.io#1]

**Comment by sijintv** [comment]
who is the designer/artist here? design one and push

**Comment by sreecodeslayer** [comment]
![silicon-labs-green-sl](https://cloud.githubusercontent.com/assets/5737888/15634954/c17a944c-25ee-11e6-9a3f-e6d99c373f18.png)

comments

**Comment by tachyons** [comment]
Single color ?

**Comment by sreecodeslayer** [comment]
![logo-1-sl-mix-2](https://cloud.githubusercontent.com/assets/5737888/15635147/4ac5c514-25f4-11e6-9f99-1b8df7b7847d.png)
1

![logo-1-sl-mix-3](https://cloud.githubusercontent.com/assets/5737888/15635148/4ace91b2-25f4-11e6-8576-478bac995cf8.png)
2

![logo-1-sl-mix-1](https://cloud.githubusercontent.com/assets/5737888/15635149/4ad56b7c-25f4-11e6-9c2f-0ad34c2a31d4.png)
3

![logo-4](https://cloud.githubusercontent.com/assets/5737888/15635151/5a691336-25f4-11e6-8300-49d7f04e4940.png)
4

**Comment by sijintv** [comment]
choose one and push

**Comment by sijintv** [comment]
i think the last one with full orange is fine for me

**Comment by sreecodeslayer** [comment]
@tachyons  did not like the plain colors. :laughing: 
@imAKHILc your thoughts?

**Comment by imakhilc** [comment]
#2097F5 🐼🐼

**Comment by tachyons** [comment]
Google or M$ logo which I mentioned didn't had any fancy colors :-)

**Comment by sreecodeslayer** [comment]
These are from Google Material Color palettes :thought_balloon:

**Comment by sreecodeslayer** [comment]
![silicon-labs-blue-sl](https://cloud.githubusercontent.com/assets/5737888/15650116/f388d994-2693-11e6-95f7-69f68f9c60f8.png)

@imAKHILc

**Comment by sreecodeslayer** [comment]
poke!

**Comment by imakhilc** [comment]
![sample](https://cloud.githubusercontent.com/assets/7577223/15803956/4040cbc2-2b15-11e6-9fcc-ed1d1cd92ddd.jpg)

**Comment by tachyons** [comment]
Looks better , check clarity of low resolution version

**Comment by imakhilc** [comment]
It's just a screenshot! Hence low res.

**Comment by imakhilc** [comment]
![sample](https://cloud.githubusercontent.com/assets/7577223/15804816/49898674-2b33-11e6-90cd-9667c3b000cf.png)

**Comment by sijintv** [comment]
@imAKHILc ... @tachyons  says to check the visibility of logo in low size so that others can still make out what we ment like letters S and L

And i have checked.. its fine :+1:

**Comment by tachyons** [comment]
@tvsijin Exactly :+1: 
Also check this for inspiration [link](https://www.google.co.in/search?q=sl+logo&safe=active&client=ubuntu&hs=qUV&channel=fs&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjNvpTb4JLNAhUBQY8KHcjFD6sQ_AUIBygB&biw=1855&bih=953)

**Comment by imakhilc** [comment]
![image](https://cloud.githubusercontent.com/assets/7577223/15813571/b5cc2d46-2bdd-11e6-9ff8-c47afddc0af7.png)

:|

![image](https://cloud.githubusercontent.com/assets/7577223/15813589/ddc78002-2bdd-11e6-8221-842b0b06c5c4.png)

The logo I inspired from ^

**Comment by sreecodeslayer** [comment]
![logo-sl](https://cloud.githubusercontent.com/assets/5737888/15902869/c30f4592-2dc7-11e6-9015-5b2a09d496b3.png)
1

![logo-sl-light-orange](https://cloud.githubusercontent.com/assets/5737888/15902870/c37def7e-2dc7-11e6-904c-35161a046974.png)
2

![logo-sl-orange](https://cloud.githubusercontent.com/assets/5737888/15902871/c382a7a8-2dc7-11e6-968e-9deb0c2ddb3d.png)
3

**Comment by tachyons** [comment]
@sreecodeslayer First one have less strain to eyes

**Comment by sreecodeslayer** [comment]
![logo-hex-y-v](https://cloud.githubusercontent.com/assets/5737888/15923350/67831a18-2e4a-11e6-987d-b455eee7fc40.png)
1
![logo-hex](https://cloud.githubusercontent.com/assets/5737888/15923351/6787222a-2e4a-11e6-9f99-c9c16207fa3d.png)
2
![logo-hex-lb-v](https://cloud.githubusercontent.com/assets/5737888/15923373/87b8a1e0-2e4a-11e6-8481-776ebfe5e9fb.png)
3
![logo-hex-trans](https://cloud.githubusercontent.com/assets/5737888/15923483/10618052-2e4b-11e6-864f-5aa7b34ad658.png)
4 - transparent bg

**Comment by sreecodeslayer** [comment]
Poke

**Comment by sijintv** [comment]
poke

**Comment by tachyons** [comment]
Poke

**Comment by sijintv** [comment]
temperately choosing [this](https://cloud.githubusercontent.com/assets/5737888/15650116/f388d994-2693-11e6-95f7-69f68f9c60f8.png) as logo and closing issue

**Comment by sijintv** [comment]
its not so visible in low size ryt :-1:

**Comment by tachyons** [comment]
@tvsijin Testing comment from telegram

**Comment by sreecodeslayer** [comment]
close it for the time being! :+1:
