### ISSUE TITLE
Ripple menu looks odd in firefox

### ISSUE THREAD

**Issue by tachyons** [silicon-labs/silicon-labs.github.io#2]
![screenshot from 2016-06-27 15-53-40](https://cloud.githubusercontent.com/assets/3112976/16376720/789591da-3c7f-11e6-8ab9-82cf1184eb7d.png)

**Comment by sreecodeslayer** [comment]
![screenshot 9](https://cloud.githubusercontent.com/assets/5737888/16376791/e0890a74-3c7f-11e6-9a6f-66259b088315.png)
Looks fine on mine. How can i reproduce the bug? :thought_balloon:

**Comment by tachyons** [comment]
@sreecodeslayer Latest ff in ubuntu

**Comment by tachyons** [comment]
😐
