### ISSUE TITLE
Treat count down widget to be added 

### ISSUE THREAD

**Issue by tachyons** [silicon-labs/silicon-labs.github.io#3]
Treat count down widget

**Comment by sijintv** [comment]
give me 5 mins

**Comment by sijintv** [comment]
added

**Comment by tachyons** [comment]
@tvsijin 👍

**Comment by tachyons** [comment]
Not working properly in firefox

**Comment by sijintv** [comment]
Let me check

**Comment by sreecodeslayer** [comment]
![screenshot 1](https://cloud.githubusercontent.com/assets/5737888/16477770/50469528-3eb2-11e6-88db-7e0020391c20.png)

![screenshot 2](https://cloud.githubusercontent.com/assets/5737888/16477769/5040b8f6-3eb2-11e6-9262-19c2334e17fc.png)

getting like this. :thought_balloon: 

Please fix this issue ASAP , treat gadgets are getting ready

**Comment by sijintv** [comment]
issue is with css.. see the height of <html> element

fixing..

**Comment by sijintv** [comment]
html import is not currently supported in firefox :3 thank you. :P 

have to put it inline btw. @tachyons

**Comment by tvsijin** [comment]
#

**Comment by tachyons** [comment]
https://hacks.mozilla.org/2014/12/mozilla-and-web-components/

**Comment by sreecodeslayer** [comment]
😆

**Comment by tachyons** [comment]
@sreecodeslayer Telegram 🙄
